agents:
  code_review:
    enabled: true
    auto_approve_minor: false
    required_score: 7
  security:
    enabled: true
    block_on_critical: true
    notify_slack: true
  auto_merge:
    enabled: true
    conditions:
      - required_reviews: 2
      - all_checks_pass: true
      - no_conflicts: true
      - branch_protection: true
  integrity:
    enabled: true
    cleanup_schedule: "0 0 * * *"

rules:
  max_pr_size: 500
  require_tests: true
  require_docs: true
  protected_branches:
    - main
    - production
