#!/usr/bin/env node

/**
 * build_reports_index.js — Scans docs/reports/ and rebuilds docs/index.md
 * with a table of all published Markdown reports.
 *
 * Usage:
 *   node scripts/build_reports_index.js [--docs-dir docs]
 *
 * Produces a clean index.md that works as a GitHub Pages landing page.
 */

import { readdirSync, statSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, basename } from "node:path";

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

const docsDir = process.argv.includes("--docs-dir")
  ? process.argv[process.argv.indexOf("--docs-dir") + 1]
  : "docs";

const reportsDir = join(docsDir, "reports");
const indexPath = join(docsDir, "index.md");

// ---------------------------------------------------------------------------
// Collect report files
// ---------------------------------------------------------------------------

if (!existsSync(reportsDir)) {
  mkdirSync(reportsDir, { recursive: true });
}

const reports = readdirSync(reportsDir)
  .filter((f) => f.endsWith(".md") && f !== "index.md")
  .map((f) => {
    const full = join(reportsDir, f);
    const stat = statSync(full);
    return {
      name: f,
      path: `reports/${f}`,
      modified: stat.mtime,
    };
  })
  .sort((a, b) => b.modified - a.modified); // newest first

// ---------------------------------------------------------------------------
// Extract metadata from filename
// ---------------------------------------------------------------------------

function extractDate(filename) {
  // Match patterns like report_20250601T120000.md or agents-summary-20250601T120000.md
  const match = filename.match(/(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})/);
  if (match) {
    const [, y, m, d, hh, mm] = match;
    return `${y}-${m}-${d} ${hh}:${mm}`;
  }
  return "—";
}

function extractType(filename) {
  if (filename.startsWith("report_")) return "Agents Run";
  if (filename.startsWith("agents-summary")) return "Summary";
  if (filename.includes("security")) return "Security Audit";
  if (filename.includes("weekly")) return "Weekly Audit";
  return "Report";
}

// ---------------------------------------------------------------------------
// Build index.md
// ---------------------------------------------------------------------------

const lines = [];

lines.push("---");
lines.push("layout: default");
lines.push("title: BSU Reports");
lines.push("---");
lines.push("");
lines.push("# BSU Enterprise Reports");
lines.push("");
lines.push("> Automated agent reports published via CI/CD pipeline.");
lines.push("");
lines.push("---");
lines.push("");

if (reports.length === 0) {
  lines.push("*No reports published yet. Run the agents pipeline to generate the first report.*");
  lines.push("");
} else {
  lines.push(`**${reports.length}** report(s) available.`);
  lines.push("");
  lines.push("| # | Date | Type | Report |");
  lines.push("|---|------|------|--------|");

  reports.forEach((r, i) => {
    const date = extractDate(r.name);
    const type = extractType(r.name);
    const link = `[${r.name}](${r.path})`;
    lines.push(`| ${i + 1} | ${date} | ${type} | ${link} |`);
  });

  lines.push("");
}

lines.push("---");
lines.push("");
lines.push("*Index auto-generated by `build_reports_index.js` — BSU Enterprise Reporting Pipeline*");
lines.push("");

// ---------------------------------------------------------------------------
// Write
// ---------------------------------------------------------------------------

writeFileSync(indexPath, lines.join("\n"), "utf-8");
console.log(`Index written to ${indexPath} (${reports.length} report(s))`);
