#!/usr/bin/env node

/**
 * json_to_md.js — Converts BSU agent JSON reports to Markdown.
 *
 * Usage:
 *   node scripts/json_to_md.js <input.json> <output.md>
 *
 * The JSON input can be:
 *   - A single report object  { timestamp, agents: [...], summary }
 *   - An array of section objects  [{ name, status, details }]
 *
 * Output: A clean, human-readable Markdown report suitable for GitHub Pages.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { basename } from "node:path";

const [inputPath, outputPath] = process.argv.slice(2);

if (!inputPath || !outputPath) {
  console.error("Usage: node json_to_md.js <input.json> <output.md>");
  process.exit(1);
}

let raw;
try {
  raw = readFileSync(inputPath, "utf-8");
} catch (err) {
  console.error(`Failed to read ${inputPath}: ${err.message}`);
  process.exit(1);
}

let data;
try {
  data = JSON.parse(raw);
} catch (err) {
  console.error(`Invalid JSON in ${inputPath}: ${err.message}`);
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Render helpers
// ---------------------------------------------------------------------------

function statusBadge(status) {
  if (!status) return "";
  const s = String(status).toLowerCase();
  if (s === "pass" || s === "passed" || s === "success" || s === "ok")
    return "PASS";
  if (s === "fail" || s === "failed" || s === "error") return "FAIL";
  if (s === "warn" || s === "warning") return "WARN";
  return status.toUpperCase();
}

function renderFindings(findings) {
  if (!findings || !Array.isArray(findings) || findings.length === 0) return "";
  const lines = findings.map((f) => {
    if (typeof f === "string") return `- ${f}`;
    const severity = f.severity ? ` [${f.severity.toUpperCase()}]` : "";
    return `- ${f.message || f.description || JSON.stringify(f)}${severity}`;
  });
  return lines.join("\n");
}

function renderSection(section) {
  const lines = [];
  const name = section.name || section.agent || section.step || "Unknown";
  const badge = statusBadge(section.status);
  lines.push(`### ${name} ${badge ? `— ${badge}` : ""}`);
  lines.push("");

  if (section.description) {
    lines.push(section.description);
    lines.push("");
  }

  if (section.details) {
    if (typeof section.details === "string") {
      lines.push(section.details);
    } else {
      lines.push("```json");
      lines.push(JSON.stringify(section.details, null, 2));
      lines.push("```");
    }
    lines.push("");
  }

  if (section.findings) {
    lines.push("**Findings:**");
    lines.push(renderFindings(section.findings));
    lines.push("");
  }

  if (section.recommendations && Array.isArray(section.recommendations)) {
    lines.push("**Recommendations:**");
    section.recommendations.forEach((r) => lines.push(`- ${r}`));
    lines.push("");
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Build the Markdown document
// ---------------------------------------------------------------------------

const md = [];
const timestamp = data.timestamp || new Date().toISOString();
const title = data.title || `BSU Agents Report — ${timestamp}`;

md.push(`# ${title}`);
md.push("");
md.push(`> Generated: ${timestamp}  `);
md.push(`> Source: \`${basename(inputPath)}\``);
md.push("");
md.push("---");
md.push("");

// If top-level is an array, treat each element as a section
const sections = Array.isArray(data) ? data : data.agents || data.sections || data.results;

if (sections && Array.isArray(sections)) {
  md.push("## Agent Results");
  md.push("");
  sections.forEach((s) => md.push(renderSection(s)));
} else {
  // Fallback: render the entire object as formatted JSON
  md.push("## Report Data");
  md.push("");
  md.push("```json");
  md.push(JSON.stringify(data, null, 2));
  md.push("```");
  md.push("");
}

// Summary section
if (data.summary) {
  md.push("---");
  md.push("");
  md.push("## Summary");
  md.push("");
  if (typeof data.summary === "string") {
    md.push(data.summary);
  } else {
    md.push("| Metric | Value |");
    md.push("|--------|-------|");
    for (const [k, v] of Object.entries(data.summary)) {
      md.push(`| ${k} | ${v} |`);
    }
  }
  md.push("");
}

md.push("---");
md.push("");
md.push("*Report generated by BSU Enterprise Reporting Pipeline*");
md.push("");

try {
  writeFileSync(outputPath, md.join("\n"), "utf-8");
  console.log(`Markdown report written to ${outputPath}`);
} catch (err) {
  console.error(`Failed to write ${outputPath}: ${err.message}`);
  process.exit(1);
}
