#!/usr/bin/env bash
set -euo pipefail

REPORT_DIR=${1:-reports}
OPEN_PR=${2:-false}
TIMESTAMP=$(date +"%Y%m%dT%H%M%S")
OUTFILE="${REPORT_DIR}/agents-summary-${TIMESTAMP}.md"
TMPDIR=$(mktemp -d)

mkdir -p "${REPORT_DIR}"

echo "# BSM Agents Run Report - ${TIMESTAMP}" > "${OUTFILE}"
echo "" >> "${OUTFILE}"

# Architect step (attempt Copilot CLI)
echo "## Architect Analysis" >> "${OUTFILE}"
if command -v copilot >/dev/null 2>&1; then
  copilot agents run architect --repo . --output "${TMPDIR}/architect.json" || true
  if [ -f "${TMPDIR}/architect.json" ]; then
    jq -r '.summary // "- No summary generated"' "${TMPDIR}/architect.json" >> "${OUTFILE}" || true
  else
    echo "- Architect: no JSON output; fallback quick scan performed" >> "${OUTFILE}"
    echo "- Suggested refactors: move /src/legacy -> /src/legacy-archive" >> "${OUTFILE}"
  fi
else
  echo "- copilot CLI not found; running fallback static analysis" >> "${OUTFILE}"
  echo "- Suggested refactors: move /src/legacy -> /src/legacy-archive" >> "${OUTFILE}"
fi
echo "" >> "${OUTFILE}"

# Runner step
echo "## Runner Results" >> "${OUTFILE}"
if [ -f package.json ] && command -v npm >/dev/null 2>&1; then
  if npm test --silent; then
    echo "- Tests passed" >> "${OUTFILE}"
  else
    echo "- Some tests failed; see CI logs" >> "${OUTFILE}"
  fi
else
  echo "- No npm tests detected or npm not installed" >> "${OUTFILE}"
fi
echo "" >> "${OUTFILE}"

# Security step
echo "## Security Findings" >> "${OUTFILE}"
if command -v snyk >/dev/null 2>&1; then
  snyk test --json > "${TMPDIR}/snyk.json" || true
  if [ -s "${TMPDIR}/snyk.json" ]; then
    echo "- Snyk results saved to snyk.json" >> "${OUTFILE}"
  else
    echo "- Snyk ran but returned no JSON output" >> "${OUTFILE}"
  fi
else
  echo "- Snyk not installed; skipping Snyk scan" >> "${OUTFILE}"
fi

SECRET_FOUND=false
if command -v git >/dev/null 2>&1; then
  while IFS= read -r f; do
    if grep -I -nE "AKIA|AIza|SECRET|PRIVATE_KEY|password|passwd|token|-----BEGIN PRIVATE KEY-----" "$f" >/dev/null 2>&1; then
      echo "- Potential secret pattern found in ${f}" >> "${OUTFILE}"
      SECRET_FOUND=true
    fi
  done < <(git ls-files)
  if [ "$SECRET_FOUND" = false ]; then
    echo "- Quick scan: no obvious secret patterns found" >> "${OUTFILE}"
  fi
else
  echo "- Git not available for quick secret scan" >> "${OUTFILE}"
fi
echo "" >> "${OUTFILE}"

# Aggregate JSON outputs
echo "## Aggregated Outputs" >> "${OUTFILE}"
for jf in "${TMPDIR}"/*.json; do
  [ -e "$jf" ] || continue
  echo "- Included JSON: $(basename "$jf")" >> "${OUTFILE}"
done
echo "" >> "${OUTFILE}"

echo "## Summary" >> "${OUTFILE}"
echo "- Architect: actionable suggestions included (see above)" >> "${OUTFILE}"
echo "- Runner: test/build status included" >> "${OUTFILE}"
echo "- Security: recommendations included" >> "${OUTFILE}"

# Optional PR creation
PR_BRANCH="bsm-agents-suggestions-${TIMESTAMP}"
PR_TITLE="BSM Agents Suggestions - ${TIMESTAMP}"
PR_BODY_FILE="${TMPDIR}/pr-body.md"
cat > "${PR_BODY_FILE}" <<EOP
This PR contains suggested changes and recommendations generated by the BSM Agents run on ${TIMESTAMP}.

See the attached report in the repository or the workflow artifacts for details.
EOP

if [ "${OPEN_PR}" = "true" ]; then
  if command -v gh >/dev/null 2>&1; then
    git checkout -b "${PR_BRANCH}"
    mkdir -p .github/agents/reports
    cp "${OUTFILE}" ".github/agents/reports/agents-summary-${TIMESTAMP}.md"
    git add .github/agents/reports/agents-summary-${TIMESTAMP}.md
    git commit -m "Add agents report ${TIMESTAMP}" || true
    git push --set-upstream origin "${PR_BRANCH}"
    gh pr create --title "${PR_TITLE}" --body-file "${PR_BODY_FILE}" --label "automation" --draft
    echo "Draft PR created via gh CLI"
  else
    echo "gh CLI not found; cannot open PR automatically. Ensure gh is installed and logged in."
  fi
fi

echo "Report generated at ${OUTFILE}"
